//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "126.2.18+g3647d39+chromium-126.0.6478.183"
#define CEF_VERSION_MAJOR 126
#define CEF_VERSION_MINOR 2
#define CEF_VERSION_PATCH 18
#define CEF_COMMIT_NUMBER 3019
#define CEF_COMMIT_HASH "3647d39e700c215bd78172c5964eb1c550950f0f"
// clang-format on

#endif // CefVersion
