//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "127.3.5+g114ea2a+chromium-127.0.6533.120"
#define CEF_VERSION_MAJOR 127
#define CEF_VERSION_MINOR 3
#define CEF_VERSION_PATCH 5
#define CEF_COMMIT_NUMBER 3037
#define CEF_COMMIT_HASH "114ea2af1ba9da18c4ac5e599ccdbb17d01ba75a"
// clang-format on

#endif // CefVersion
