//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "142.0.15+g6dfdb28+chromium-142.0.7444.176"
#define CEF_VERSION_MAJOR 142
#define CEF_VERSION_MINOR 0
#define CEF_VERSION_PATCH 15
#define CEF_COMMIT_NUMBER 3314
#define CEF_COMMIT_HASH "6dfdb28d752a47e189d7a23b01f368ab0bdb378d"
// clang-format on

#endif // CefVersion
