name: Build on macOS-x86_64

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-macos-x86_64.yml'
      - 'CMakeLists.txt'
      - 'CefViewCore'
      - 'example/**'
      - 'include/**'
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-macos-x86_64.yml'
      - 'CMakeLists.txt'
      - 'CefViewCore'
      - 'example/**'
      - 'include/**'
      - 'src/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          setup-python: 'true'
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14'

      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Cache CEF folders
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/CefViewCore/dep
          key: ${{ runner.os }}-core-dep-cef

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -G "Xcode" -B ${{github.workspace}}/build -DPROJECT_ARCH=x86_64 -DBUILD_DEMO=ON -DUSE_SANDBOX=ON -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install

      - name: Build QCefView
        run: xcodebuild -project ${{github.workspace}}/build/QCefView.xcodeproj -target QCefView -configuration ${{env.BUILD_TYPE}}

      - name: Build QCefViewTest
        run: xcodebuild -project ${{github.workspace}}/build/QCefView.xcodeproj -target QCefViewTest -configuration ${{env.BUILD_TYPE}}

      - name: Install
        if: github.event_name != 'pull_request'
        # Collect the output
        run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Create SDK artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        # Upload artifact
        with:
          name: QCefView.macos.x86_64
          path: ${{github.workspace}}/out/install/QCefView

      - name: Create Demo artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        # Upload artifact
        with:
          name: QCefViewTest.macos.x86_64
          path: ${{github.workspace}}/out/install/QCefViewTest

    #- name: Test
    #working-directory: ${{github.workspace}}/build
    # Execute tests defined by the CMake configuration.
    # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #run: ctest -C ${{env.BUILD_TYPE}}
